# Generated by Django 6.0.5 on 2026-05-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inbox', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermata'), ('cancelled', 'Annullata')], default='pending', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('ambiguities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_draft', to='inbox.message')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_product_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drafts.orderdraft')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
