# Generated by Django 6.0.5 on 2026-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraftitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
