# Generated by Django 6.0.5 on 2026-05-08 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_orderdraftitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdraft',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderdraft',
            name='status',
            field=models.CharField(choices=[('pending', 'In Attesa'), ('processing', 'In Lavorazione'), ('completed', 'Ultimata')], default='pending', max_length=20),
        ),
    ]
