# Generated by Django 6.0.5 on 2026-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_orderdraft_assigned_to_orderdraft_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdraftitem',
            name='raw_product_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='orderdraftitem',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
