# Generated by Django 6.0.5 on 2026-05-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('manual', 'Manual')], max_length=20)),
                ('sender', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Nuovo'), ('analyzing', 'In analisi'), ('drafted', 'Bozza generata'), ('clarification', 'Richiede chiarimento'), ('converted', 'Convertito in ordine'), ('not_order', 'Non è un ordine'), ('archived', 'Archiviato'), ('error', 'Errore')], default='new', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
